from .students_routes import student_bp
from .practice_units_routes import practice_unit_bp
from .practice_statistics_routes import practice_statistics_bp
from .practice_answers_routes import practice_answers_bp
from .practice_questions_routes import practice_questions_bp